id: A0DCE4B24
title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer to Mahākāla
  and Consort'
type: translation
pechas:
- IA1A6A11D
- IA4B5D8B5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:09:58.530312
  last_modified_at: 2023-01-04 12:09:58.530322
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IA1A6A11D/DEEE: A40A
  IA4B5D8B5/90A9: A40A
